[package]
name = "openfairdb"
version = "0.3.8"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]
license = "AGPL-3.0-or-later"

[dependencies]
clap = "2"
log = "0.4"
env_logger = "0.5"
uuid = { version = "0.7", features = ["v4"] }
url = "1"
failure = "*"
quick-error = "1"
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = "1"
serde_json = "1"
serde_derive = "1"
chrono = "0.4"
lazy_static = "1"
lettre = "0.8"
lettre_email = "0.8"
regex = "1"
pwhash = "0.2"
fast_chemail = "0.9"
toml = "0.4"
dotenv = "0.13"
diesel = { version = "1.3", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "1.3", features = ["sqlite"]  }
libsqlite3-sys = { version = "*", features = ["bundled"] }
csv = "1"

[features]
default = ["email"]
email = []
