[package]
name = "openfairdb"
version = "0.9.3"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>", "slowtec GmbH <post@slowtec.de>"]
keywords = ["geo", "fair", "sustainability"]
homepage = "https://github.com/kartevonmorgen/openfairdb"
repository = "https://github.com/kartevonmorgen/openfairdb"
license = "AGPL-3.0-or-later"
edition = "2018"

[patch.crates-io]
ofdb-boundary = { path = "ofdb-boundary" }
ofdb-core = { path = "ofdb-core" }
ofdb-entities = { path = "ofdb-entities" }
ofdb-gateways = { path = "ofdb-gateways" }
captcha = { git = "https://github.com/kartevonmorgen/captcha", branch = "updates" }

[workspace]
members = [
  "ofdb-boundary",
  "ofdb-core",
  "ofdb-entities",
  "ofdb-gateways",
]
exclude = [ "ofdb-app", "ofdb-app-clearance" ]

[dependencies]
anyhow = "*"
captcha = "*"
chrono = "*"
# clap 3 is supposed to introduce breaking changes
clap = "2"
csv = "*"
diesel = { version = "*", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = { version = "*", features = ["sqlite"] }
dotenv = "*"
env_logger = "*"
# failure is only required for TantivyError
failure = "*"
fast_chemail = "*"
lazy_static = "*"
log = "*"
num-traits = "*"
maud = { version = "*", optional = true, features = ["rocket"] }
ofdb-boundary = "*"
ofdb-core = "*"
ofdb-entities = "*"
ofdb-gateways = "*"
owning_ref = "*"
passwords = "*"
pwhash = "*"
regex = "*"
rocket = "*"
rocket_contrib = "*"
rocket_cors = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
strum = "*"
tantivy = "*"
time = "0.1"
thiserror = "1"
url = { version = "2", features = ["serde"] }
uuid = { version = "*", features = ["v4"] }

[dev-dependencies]
rand = "*"
ofdb-boundary = { version = "*", features = ["extra-derive"] }
ofdb-entities = { version = "*", features = ["builders"] }

[build-dependencies]
walkdir = "2"

[features]
default = ["frontend", "email", "clearance", "app"]

app = []
clearance = []
email = []
frontend = ["maud"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
