[package]
name = "openfairdb"
version = "0.4.2-dev"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>", "slowtec GmbH <post@slowtec.de>"]
keywords = ["geo", "fair", "sustainability"]
homepage = "https://github.com/slowtec/openfairdb"
repository = "https://github.com/slowtec/openfairdb"
license = "AGPL-3.0-or-later"
edition = "2018"

[patch.crates-io]
geocoding = { git = "https://github.com/georust/geocoding" }

[dependencies]
# clap 3 is supposed to introduce breaking changes
chrono = "*"
clap = "2"
csv = "*"
diesel = { version = "*", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "*", features = ["sqlite"]  }
dotenv = "*"
env_logger = "*"
fast_chemail = "*"
geocoding = "*"
lazy_static = "*"
log = "*"
num-derive = "*"
num-traits = "*"
openssl = { version = "*", features = ["vendored"] }
passwords = "*"
pwhash = "*"
quick-error = "*"
quoted_printable = "*"
regex = "*"
rocket = "*"
rocket_contrib = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
slug = "*"
toml = "*"
url = "*"
uuid = { version = "*", features = ["v4"] }

[features]
default = ["email"]
email = []
