[package]
name = "openfairdb"
version = "0.1.1"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]

[dependencies]
r2d2 = "0.7"
clap = "2.4"
log = "0.3"
slog-envlogger = "0.5"
uuid = { version = "0.3", features = ["v4"] }
rusted_cypher = "1.0"
r2d2_cypher = "0.2"
url = "1.4"
quick-error = "1.1"
emailaddress = "0.3"
rocket = "0.2"
rocket_codegen = "0.2"
rocket_contrib = "0.2"
lazy_static = "0.2"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
chrono = "0.2"

[dev-dependencies.rocket]
version = "0.2"
features = ["testing"]
