[package]
name = "ofdb-core"
version = "0.0.0" # will stay 0.0.0 until published
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "*"
chrono = "*"
itertools = "*"
num-derive = "*"
num-traits = "*"
uuid = { version = "*", features = ["v4"] }
url = "2"
pwhash = "*"
strum = "*"
strum_macros = "*"

[dev-dependencies]
rand = "*"
