[package]
name = "ofdb-gateways"
version = "0.0.0" # will stay 0.0.0 until published
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2018"
publish = false

[dependencies]
chrono = "*"
fast_chemail = "*"
geocoding = "*"
itertools = "*"
lazy_static = "*"
log = "*"
reqwest = "0.9" # TODO: update to v0.10.x
ofdb-entities = "*"
quoted_printable = "*"
url = "2"
