[package]
name = "ofdb-boundary"
version = "0.0.0" # will stay 0.0.0 until published
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2018"
publish = false

[dependencies]
ofdb-entities = "*"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
url = { version = "2", features = ["serde"] }

[features]
default = []
extra-derive = []
