[package]
name = "ofdb-entities"
version = "0.0.0" # will stay 0.0.0 until published
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2018"
publish = false

[dependencies]
bs58 = "*"
chrono = "*"
itertools = "*"
num-derive = "*"
num-traits = "*"
pwhash = "*"
uuid = { version = "*", features = ["v4"] }
url = "2"
strum = "*"
strum_macros = "*"

[dev-dependencies]
rand = "*"
